// Shared utilities used by every per-site content script.
// Exposed as window.AIBlocker so instagram.js / twitter.js / facebook.js /
// linkedin.js / reddit.js / tiktok.js can consume it.
(function () {
  const LABEL_PATTERNS = [
    /\bai[\s-]?info\b/i,
    /\bmade with ai\b/i,
    /\bai[\s-]?generated\b/i,
    /\bimagined with ai\b/i,
    /\bcreated with ai\b/i,
    /\bgenerated with ai\b/i,
    /\bai generated content\b/i,
    /\bthis (image|video|photo) was generated by ai\b/i
  ];

  // Weaker signals: several must co-occur (see scoreHeuristic) before a post
  // is treated as "suspected" AI content, to keep false positives low.
  const HEURISTIC_KEYWORDS = [
    /#ai(art|generated|image|created)?\b/i,
    /\bmidjourney\b/i,
    /\bstable diffusion\b/i,
    /\bdall-?e\b/i,
    /\bsora\b/i,
    /\brunway ?ml\b/i,
    /\bai art\b/i,
    /\bgenerative ai\b/i,
    /\bprompt:\s/i
  ];

  // Posts whose pixel-analysis probability is at or above this are treated
  // as AI-generated. 0.75 favors precision over recall given the model is
  // unverified/local — see models/README.md.
  const PIXEL_AI_THRESHOLD = 0.75;

  // Cap per post so a 10-image carousel doesn't fire 10 inferences.
  const MAX_IMAGES_PER_POST = 3;

  const DEFAULT_SETTINGS = {
    enabled: true,
    mode: "blur",
    platforms: {
      instagram: true,
      twitter: true,
      facebook: true,
      linkedin: true,
      reddit: true,
      tiktok: true
    },
    detectLabels: true,
    detectHeuristics: true,
    pixelAnalysis: false,
    hiddenCount: 0
  };

  async function getSettings() {
    const stored = await chrome.storage.sync.get(null);
    return { ...DEFAULT_SETTINGS, ...stored };
  }

  function onSettingsChanged(callback) {
    chrome.storage.onChanged.addListener((changes, area) => {
      if (area === "sync") callback(changes);
    });
  }

  // Reddit's current frontend (<shreddit-post>) and some other sites render
  // content inside an open shadow root. This checks one level of shadow DOM
  // in addition to light DOM; it will not see closed shadow roots or nested
  // shadow trees deeper than one level, which is a known limitation.
  function queryAllDeep(root, selector) {
    const light = Array.from(root.querySelectorAll(selector));
    if (root.shadowRoot) {
      return light.concat(Array.from(root.shadowRoot.querySelectorAll(selector)));
    }
    return light;
  }

  function textOf(el) {
    if (!el) return "";
    const alt = queryAllDeep(el, "img[alt]")
      .map((img) => img.getAttribute("alt") || "")
      .join(" ");
    const aria = queryAllDeep(el, "[aria-label]")
      .map((n) => n.getAttribute("aria-label") || "")
      .join(" ");
    const titles = queryAllDeep(el, "[title]")
      .map((n) => n.getAttribute("title") || "")
      .join(" ");
    const ownText = el.shadowRoot
      ? `${el.innerText || ""} ${el.shadowRoot.textContent || ""}`
      : el.innerText || "";
    return `${ownText} ${alt} ${aria} ${titles}`;
  }

  function findExplicitLabel(el) {
    const text = textOf(el);
    for (const pattern of LABEL_PATTERNS) {
      if (pattern.test(text)) return pattern.source;
    }
    return null;
  }

  // Requires at least two distinct heuristic hits to reduce false positives
  // (a single "#ai" hashtag is common noise; two co-occurring signals is not).
  function scoreHeuristic(el) {
    const text = textOf(el);
    const hits = [];
    for (const pattern of HEURISTIC_KEYWORDS) {
      if (pattern.test(text)) hits.push(pattern.source);
    }
    return hits;
  }

  // Text/label tier only — synchronous, no network or inference involved.
  function classifyText(el, settings) {
    if (settings.detectLabels) {
      const label = findExplicitLabel(el);
      if (label) return { hidden: true, reason: "label", detail: label };
    }
    if (settings.detectHeuristics) {
      const hits = scoreHeuristic(el);
      if (hits.length >= 2) {
        return { hidden: true, reason: "heuristic", detail: hits.join(", ") };
      }
    }
    return { hidden: false };
  }

  function buildOverlay(reason, onReveal) {
    const overlay = document.createElement("div");
    overlay.className = "ai-blocker-overlay";

    const label = document.createElement("span");
    label.className = "ai-blocker-overlay-label";
    label.textContent =
      reason === "pixel"
        ? "Hidden: image looks AI-generated"
        : reason === "label"
          ? "Hidden: labeled AI-generated"
          : "Hidden: suspected AI-generated";
    overlay.appendChild(label);

    const btn = document.createElement("button");
    btn.className = "ai-blocker-overlay-btn";
    btn.type = "button";
    btn.textContent = "Show anyway";
    btn.addEventListener("click", (e) => {
      e.preventDefault();
      e.stopPropagation();
      onReveal();
    });
    overlay.appendChild(btn);

    return overlay;
  }

  // Idempotent: safe to call more than once on the same element (e.g. once
  // from the synchronous text pass, once later from the async pixel pass).
  function applyHideDecision(el, decision, settings) {
    if (!decision.hidden) return;
    if (
      el.classList.contains("ai-blocker-hidden") ||
      el.classList.contains("ai-blocker-blurred")
    ) {
      return;
    }

    // The one place all three detection tiers converge — logs which path
    // actually caught this post. Only "pixel" should ever cost a quota
    // unit; "label" and "heuristic" are free/unlimited by design (see
    // [[Freemium Gating]]) and should never show a quota tally attached.
    console.log(
      `[AI Post Blocker] HIDDEN via "${decision.reason}"` +
        (decision.detail ? ` (${decision.detail})` : "") +
        (decision.reason === "pixel" ? " — quota-metered" : " — free, unlimited")
    );

    el.classList.add(
      settings.mode === "hide" ? "ai-blocker-hidden" : "ai-blocker-blurred"
    );

    if (settings.mode === "blur") {
      const overlay = buildOverlay(decision.reason, () => {
        el.classList.remove("ai-blocker-blurred");
        overlay.remove();
      });
      el.style.position = el.style.position || "relative";
      el.appendChild(overlay);
    }

    chrome.runtime.sendMessage({ type: "POST_HIDDEN", reason: decision.reason });
  }

  // Candidate <img> media for pixel analysis, filtered to drop small
  // avatar/icon/emoji images that aren't worth the inference cost. Returns
  // pixel-analysis targets in the { kind: 'url', value, cacheKey } shape
  // analyzePixelsIfEligible expects.
  function getContentImages(el, { minSize = 150 } = {}) {
    return queryAllDeep(el, "img[src]")
      .filter((img) => {
        const w = img.naturalWidth || img.width || 0;
        const h = img.naturalHeight || img.height || 0;
        return w >= minSize && h >= minSize;
      })
      .map((img) => {
        const value = img.currentSrc || img.src;
        return { kind: "url", value, cacheKey: value };
      });
  }

  function clearHideState(el) {
    el.classList.remove("ai-blocker-hidden", "ai-blocker-blurred");
    el.querySelector(":scope > .ai-blocker-overlay")?.remove();
  }

  // Set once the background/offscreen pipeline reports the free daily
  // pixel-analysis allowance is used up (see [[Freemium Gating]] in
  // Obsidian). Cheap short-circuit so a long scroll session doesn't keep
  // sending doomed requests for the rest of the page's lifetime; resets
  // naturally on the next page load/injection.
  let quotaKnownExhausted = false;

  // Runs pixel analysis on a post's candidate media, but only for posts that
  // the text/label tier did NOT already flag — avoids wasted inference on
  // posts we're hiding anyway. getMediaTargets(el) is supplied per-platform
  // and returns [{ kind: 'url' | 'dataurl', value, cacheKey? }, ...].
  //
  // Label/heuristic detection above is always free and unlimited. This tier
  // is metered server-side... well, background-script-side: each call may
  // come back with { quotaExceeded: true } once the free daily allowance
  // (or an isPro override) says no — see src/background.js and
  // src/offscreen/offscreen.js for where that's enforced.
  const PIXEL_LOG = "[AI Post Blocker][pixel]";

  // Short, log-friendly identifier for a target without dumping a full
  // (potentially huge) data: URL into the console.
  function targetLabel(target) {
    if (target.kind === "dataurl") {
      return `<video frame, cacheKey=${(target.cacheKey || "").slice(0, 80)}>`;
    }
    return target.value;
  }

  async function analyzePixelsIfEligible(el, settings, getMediaTargets) {
    if (!settings.pixelAnalysis) return;
    if (quotaKnownExhausted) return;

    let targets;
    try {
      targets = getMediaTargets(el) || [];
    } catch (err) {
      console.warn(`${PIXEL_LOG} getMediaTargets() threw, skipping this post:`, err);
      return;
    }

    if (targets.length === 0) {
      // Distinguishes "genuinely no media" (not interesting, don't log) from
      // "media exists in the DOM but nothing was eligible" (interesting —
      // could mean lazy-loaded images that haven't finished loading yet,
      // everything under the size filter, or (TikTok) a failed frame-grab).
      const hasImg = queryAllDeep(el, "img").length > 0;
      const hasVideo = queryAllDeep(el, "video").length > 0;
      if (hasImg || hasVideo) {
        console.log(
          `${PIXEL_LOG} post has media (img=${hasImg} video=${hasVideo}) but extracted 0 ` +
            `pixel-analysis targets — never reached the model. Likely causes: images still ` +
            `lazy-loading (naturalWidth still 0), all below the ≥150px eligibility filter, or ` +
            `(TikTok) canvas frame-grab failed.`
        );
      }
      return;
    }

    for (const target of targets.slice(0, MAX_IMAGES_PER_POST)) {
      if (
        el.classList.contains("ai-blocker-hidden") ||
        el.classList.contains("ai-blocker-blurred")
      ) {
        return; // already hidden by an earlier target or a race with the text tier
      }

      const label = targetLabel(target);
      const message = {
        type: "CLASSIFY_IMAGE_PIXELS",
        cacheKey: target.cacheKey || target.value
      };
      if (target.kind === "dataurl") message.imageDataUrl = target.value;
      else message.imageUrl = target.value;

      let result;
      try {
        result = await chrome.runtime.sendMessage(message);
      } catch (err) {
        // Background/offscreen document unreachable entirely — not a fetch
        // or CORS problem, the message never got a response at all.
        console.warn(`${PIXEL_LOG} message channel unreachable, image never reached the model: ${label}`, err);
        continue;
      }

      if (result?.quotaExceeded) {
        quotaKnownExhausted = true;
        console.log(`${PIXEL_LOG} QUOTA EXCEEDED — image never reached the model: ${label}`);
        return;
      }

      if (result?.error) {
        // stage distinguishes where it died: 'fetch-network' (fetch() threw
        // — opaque by browser design, could be CORS/host_permission/DNS/
        // network), 'fetch-http' (fetch() resolved but !response.ok — NOT a
        // CORS issue, the request went through and the server itself
        // rejected it), or 'decode' (createImageBitmap threw — corrupt or
        // unsupported image data, not a network problem at all).
        console.warn(
          `${PIXEL_LOG} DROPPED before scoring [stage=${result.stage || "unknown"}]: ${label} — ${result.error}`
        );
        continue;
      }

      if (typeof result?.aiProbability === "number") {
        const p = result.aiProbability;
        const crosses = p >= PIXEL_AI_THRESHOLD;
        // Quota tally only present on a fresh (non-cached) scan — a cache
        // hit doesn't cost a scan, so there's nothing new to report here.
        // If you see SCORED lines piling up without "[quota N/M]" attached,
        // every hit is a cache hit and the counter has no reason to move.
        const quotaTag = result.quota
          ? ` [quota ${result.quota.used}/${result.quota.limit}]`
          : result.cached
            ? " [cache hit, no quota cost]"
            : "";
        // Logged unconditionally — this is the raw score, before
        // thresholding, for every image that actually made it to the model.
        console.log(
          `${PIXEL_LOG} SCORED p=${p.toFixed(3)} (threshold=${PIXEL_AI_THRESHOLD}) → ` +
            `${crosses ? "HIDE" : "keep visible"}${quotaTag}: ${label}`
        );
        if (crosses) {
          applyHideDecision(
            el,
            { hidden: true, reason: "pixel", detail: `p=${p.toFixed(2)}` },
            settings
          );
          return;
        }
      }
    }
  }

  // Warns once if a post selector never matches anything within warnAfterMs —
  // a strong signal the platform changed its markup and detection is dead.
  function warnIfSelectorStale(getContainers, hasFoundAny, opts) {
    const { platform, selectorDescription, warnAfterMs = 10000 } = opts;
    if (!platform) return;
    setTimeout(() => {
      if (hasFoundAny()) return;
      console.warn(
        `[AI Post Blocker] ${platform}: selector "${selectorDescription}" matched 0 posts ` +
          `after ${warnAfterMs}ms. The site likely changed its markup — detection may be broken.`
      );
    }, warnAfterMs);
  }

  function observeFeed(getContainers, onFound, opts = {}) {
    const seen = new WeakSet();
    let foundAny = false;

    const scan = () => {
      for (const el of getContainers()) {
        if (seen.has(el)) continue;
        seen.add(el);
        foundAny = true;
        onFound(el); // onFound may be async; intentionally not awaited here
      }
    };

    scan();
    const observer = new MutationObserver(() => scan());
    observer.observe(document.body, { childList: true, subtree: true });

    warnIfSelectorStale(getContainers, () => foundAny, opts);

    return observer;
  }

  window.AIBlocker = {
    getSettings,
    onSettingsChanged,
    classifyText,
    applyHideDecision,
    clearHideState,
    analyzePixelsIfEligible,
    observeFeed,
    queryAllDeep,
    getContentImages
  };
})();
